# Generated by Django 6.0 on 2025-12-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='사진 제목(설명)')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='슬라이드 사진')),
                ('order', models.IntegerField(default=0, verbose_name='순서(낮은순)')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
            ],
            options={
                'verbose_name': '메인 슬라이드 사진',
                'verbose_name_plural': '메인 슬라이드 사진',
            },
        ),
        migrations.AlterModelOptions(
            name='churchreview',
            options={'verbose_name': '성도 리얼 리뷰', 'verbose_name_plural': '성도 리얼 리뷰'},
        ),
        migrations.AlterModelOptions(
            name='financialtransaction',
            options={'verbose_name': '재정 입출금 내역', 'verbose_name_plural': '재정 입출금 내역'},
        ),
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'verbose_name': '주간 사역 보고서', 'verbose_name_plural': '주간 사역 보고서'},
        ),
    ]
