# Generated by Django 6.0 on 2025-12-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0002_slideimage_alter_churchreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchreview',
            options={},
        ),
        migrations.AddField(
            model_name='churchreview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='작성자 IP'),
        ),
    ]
