# Generated by Django 6.0 on 2025-12-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministry", "0003_alter_churchreview_options_churchreview_ip_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AlterModelOptions(
            name="churchreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "성도 리얼 리뷰",
                "verbose_name_plural": "성도 리얼 리뷰",
            },
        ),
    ]
