# Generated by Django 6.0 on 2025-12-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministry", "0004_notionnotice_alter_churchreview_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notionnotice",
            options={},
        ),
        migrations.AddField(
            model_name="notionnotice",
            name="files_json",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
