# Generated by Django 6.0 on 2025-12-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ministry", "0005_alter_notionnotice_options_notionnotice_files_json"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notionnotice",
            options={"ordering": ["-date"]},
        ),
    ]
