"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ministry',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Neon DB 주소가 있을 때만(배포 환경) Neon을 쓰도록 설정
# (내 컴퓨터에서는 계속 sqlite3를 써도 됩니다)
DATABASE_URL = os.environ.get("DATABASE_URL") # Vercel이 나중에 이 값을 넣어줄 겁니다.

if DATABASE_URL:
    DATABASES['default'] = dj_database_url.config(default=DATABASE_URL, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
# config/settings.py

# 기존: LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ko-kr'  # <--- 한국어로 변경

# 기존: TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Seoul' # <--- 한국 시간으로 변경 (재정 날짜 정확도를 위해 필수!)

USE_I18N = True
USE_TZ = False  # <--- True로 두면 헷갈릴 수 있으니 False로 해서 한국 시간만 쓰도록 설정 추천


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# 트렌디한 관리자 모드 디자인
JAZZMIN_SETTINGS = {
    # 1. 사이트 제목
    "site_title": "투명한 사역 교회",
    
    # 2. 로그인 화면 로고 문구
    "site_header": "Ministry Admin",
    
    # 3. 로그인 화면 환영 메시지
    "welcome_sign": "환영합니다, 목사님! (관리자 모드)",
    
    # 4. 저작권 문구
    "copyright": "Antigravity Ministry Ltd",
    
    # 5. 검색 모델 (상단 검색창에서 바로 재정 내역 검색 가능하게!)
    "search_model": ["ministry.FinancialTransaction"],
    
    # 6. 사이드바 메뉴 커스텀 (아이콘 바꾸기)
    # FontAwesome 아이콘 이름 사용 (예: fas fa-church)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        "ministry.WeeklyReport": "fas fa-chart-line",        # 주간보고 -> 차트 아이콘
        "ministry.FinancialTransaction": "fas fa-file-invoice-dollar", # 재정 -> 달러 아이콘
        "ministry.ChurchReview": "fas fa-comments",          # 리뷰 -> 말풍선 아이콘
    },
}

# 이미지 업로드 설정
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# config/settings.py 맨 아래에 추가

# 1. AWS 접속 정보 (이건 AWS 사이트에서 받아와야 함)
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = 'ap-northeast-2' # 서울 리전
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

# 2. S3 설정 (건드리지 마세요)
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_VERIFY = True


# 저장소를 S3로 교체하는 명령, 이게 없으면 로컬에 저장
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
},

}




