# Generated by Django 6.0 on 2025-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='익명', max_length=20, verbose_name='작성자')),
                ('content', models.TextField(verbose_name='후기 내용')),
                ('rating', models.IntegerField(default=5, verbose_name='별점(1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='날짜')),
                ('type', models.CharField(choices=[('IN', '수입'), ('OUT', '지출')], max_length=3, verbose_name='구분')),
                ('category', models.CharField(max_length=50, verbose_name='부서/항목')),
                ('description', models.CharField(max_length=200, verbose_name='적요(내역)')),
                ('amount', models.IntegerField(verbose_name='금액')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='기준 날짜(주일)')),
                ('worship_attendance', models.IntegerField(default=0, verbose_name='예배 인원')),
                ('new_comers', models.IntegerField(default=0, verbose_name='새가족 수')),
                ('offering_total', models.BigIntegerField(default=0, verbose_name='주간 헌금 총액')),
            ],
        ),
    ]
